<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            [
                'type' => 'client',
                'title' => 'TAMCON Infrastructure Engineering Portal',
                'client_name' => 'TAMCON Consulting Engineers',
                'category' => 'Civil Engineering & Construction',
                'technologies' => ['PHP', 'MySQL', 'LAMP Stack', 'Vanilla JS', 'AJAX'],
                'description' => 'I architected and deployed an integrated public portal and custom administrative CMS. I engineered a synchronized data pipeline to display complex civil engineering portfolios with real-time updates, contact routing, and dynamic media galleries. I used AI-assisted IDEs to optimize SQL queries and automate multi-device layout responsiveness.',
                'significant_figure' => '100% Real-time Sync',
                'problem' => 'Needed to display complex civil engineering portfolios with real-time administrative updates, fast load times under heavy graphical loads, and automated contact routing.',
                'methodology' => 'We built real-time state synchronization between administrative back-ends and public pages, combined with optimized image-handling systems to maintain sub-second load times.',
                'outcome' => 'Established a synchronized engineering portal that handles high-fidelity graphics and administrative workflows with minimal latency.',
                'image' => '/assets/images/custom-webdev.png',
                'is_featured' => true,
            ],
            [
                'type' => 'client',
                'title' => 'South Ring Autos Garage Workspace System',
                'client_name' => 'South Ring Autos',
                'category' => 'Automotive & Logistics',
                'technologies' => ['PHP', 'React', 'MySQL', 'Payment Gateways'],
                'description' => 'I designed and deployed an integrated workshop management system that supports client onboarding, vehicle service tracking, and automated client notifications. I engineered a background process engine to handle service reminders and payment tracking, leveraging AI code generation to ensure secure, error-free transaction records.',
                'significant_figure' => 'Automatic Reminders',
                'problem' => 'Needed to track vehicle service pipelines, manage client check-ins, and automate transaction logging securely across multiple roles.',
                'methodology' => 'We designed complex state machines tracking vehicle repair statuses across multiple user roles and wrote optimized database triggers for transactional reminders.',
                'outcome' => 'Achieved automated, secure scheduling and status updates, reducing drop-offs and administrative billing workloads.',
                'image' => '/assets/images/custom-webdev.png',
                'is_featured' => true,
            ],
            [
                'type' => 'client',
                'title' => 'HUCAA Interactive Networking Platform',
                'client_name' => 'Hekima University College Alumni Association',
                'category' => 'EdTech & Community Portals',
                'technologies' => ['LAMP Stack', 'React', 'WebSockets', 'Push Notification Engines'],
                'description' => 'I designed and deployed a secure, closed-access alumni directory and networking portal. I engineered a multi-tenant messaging database featuring real-time chat, dynamic event previews, and live push notifications, using AI tools to optimize database structures and secure our endpoints.',
                'significant_figure' => 'Live WebSockets Chat',
                'problem' => 'Required secure, high-concurrency communications during high-volume alumni registration periods without compromising authenticated student privacy.',
                'methodology' => 'We engineered a separation between open-access marketing pages and strictly authenticated directories, backed by real-time notification push engines.',
                'outcome' => 'Successfully connected thousands of alumni through live messaging and coordinate event coordination with zero server bottlenecks.',
                'image' => '/assets/images/digital-strategy.png',
                'is_featured' => true,
            ],
            [
                'type' => 'client',
                'title' => 'Wisdom Capital Agritech Commerce Hub',
                'client_name' => 'Wisdom Capital Limited',
                'category' => 'Agritech & E-Commerce',
                'technologies' => ['PHP', 'React', 'MySQL', 'SMTP Mail Services'],
                'description' => 'I architected a direct-to-consumer agricultural commerce ecosystem, integrating a public ordering storefront and secure delivery bookings with an administrative dashboard that tracks sales, payment statuses, and regional trends.',
                'significant_figure' => 'Transactional SMTP',
                'problem' => 'Friction in managing regional order distribution, payment verification drops, and bulky product catalog load times.',
                'methodology' => 'We implemented transactional fallback states to preserve database consistency during payment checkout drops, combined with lightweight image models.',
                'outcome' => 'Enabled direct sales and deliveries for farmers with complete tracking and analytics on payment and distribution maps.',
                'image' => '/assets/images/custom-webdev.png',
                'is_featured' => true,
            ],
            [
                'type' => 'client',
                'title' => 'Tena Digital Onboarding Platform',
                'client_name' => 'Tena',
                'category' => 'FinTech / SaaS Onboarding',
                'technologies' => ['PHP', 'React', 'JS Graphing Libraries', 'Validation Engines'],
                'description' => 'I built a digital registration portal featuring a progressive-disclosure dynamic registration form linked to an analytical PHP dashboard. I integrated high-fidelity interactive data visualizations mapping user acquisition velocities and system onboarding patterns.',
                'significant_figure' => 'Progressive Forms',
                'problem' => 'High registration drop-off rates due to complicated multi-step KYC documents and tracking user acquisition speeds.',
                'methodology' => 'We engineered client-side validation states and custom progress visualization widgets mapping user sign-up patterns.',
                'outcome' => 'Optimized user acquisition tracking and registration workflows, drastically lowering the onboarding barrier.',
                'image' => '/assets/images/digital-strategy.png',
                'is_featured' => true,
            ],
            [
                'type' => 'client',
                'title' => 'Global Harmony Initiative NGO Engagement Portal',
                'client_name' => 'Global Harmony Initiative',
                'category' => 'Non-Profit & Philanthropy',
                'technologies' => ['PHP', 'MySQL', 'AJAX', 'State Management'],
                'description' => 'I developed a dynamic digital platform designed to maximize NGO mission visibility and donor engagement. I built an asynchronous content administration back-end utilizing AJAX to perform real-time, non-blocking site updates, paired with secure donation ledger logging and public contact management structures.',
                'significant_figure' => 'Asynchronous Content',
                'problem' => 'Admin updates causing constant browser reloads, degrading operations, alongside the need for secure donation logging.',
                'methodology' => 'We formulated secure database schemas for donation records and applied AJAX routing to eliminate page refreshes.',
                'outcome' => 'Delivered an intuitive content editor and highly reliable donation pipeline tracking NGO goals and events.',
                'image' => '/assets/images/uiux-design.png',
                'is_featured' => true,
            ],
            [
                'type' => 'client',
                'title' => 'OKJStyle & Creative Brand Portfolio',
                'client_name' => 'OKJTechnologies',
                'category' => 'Creative Services & Web Agency',
                'technologies' => ['React', 'Scroll-Animations', 'Reservation State Machines'],
                'description' => 'I designed and deployed a series of highly interactive, performance-optimized visual portfolio applications. I engineered custom scroll-linked animations and asynchronous reservation engines, backed by a unified admin dashboard tracking system analytics and scheduling data.',
                'significant_figure' => 'Performance Scroll',
                'problem' => 'Low frame rates during heavy scroll animations, combined with scheduling reservation conflicts.',
                'methodology' => 'We optimized scroll bindings and rendered layout metrics efficiently to preserve 60fps, backing it with coordinate booking state machines.',
                'outcome' => 'Delivered a highly interactive experience reflecting creative agency capabilities with automated scheduling.',
                'image' => '/assets/images/uiux-design.png',
                'is_featured' => true,
            ],
            [
                'type' => 'client',
                'title' => 'Dickson Gitonga Legal Practice Automation',
                'client_name' => 'Dickson Gitonga Advocates',
                'category' => 'LegalTech & Corporate Portals',
                'technologies' => ['PHP', 'React', 'Web-Scraping', 'RBAC'],
                'description' => 'I designed a professional LegalTech portal that automates administrative workflows for legal advocates. I engineered a secure client correspondence dashboard, dynamic FAQ modules, and a customized legal notification engine designed to integrate with automated Kenya Law cause lists. Deployed with strict access controls to protect sensitive legal client records.',
                'significant_figure' => 'RBAC Secure Access',
                'problem' => 'Advocates manually querying public cause lists for court schedules, alongside the risk of sensitive client record exposure.',
                'methodology' => 'We engineered a scraper to fetch public legal directories and map alerts, protected by strict Role-Based Access Controls.',
                'outcome' => 'Automated court schedules integration with legal databases, keeping sensitive legal documents secure.',
                'image' => '/assets/images/custom-webdev.png',
                'is_featured' => true,
            ],
            [
                'type' => 'client',
                'title' => 'Mizizi Direct-to-Consumer Retail Platform',
                'client_name' => 'Mizizi Sugarcane Juice',
                'category' => 'Food & Beverage / Retail Tech',
                'technologies' => ['PHP', 'React', 'Sales Analysis Engines', 'Geolocation'],
                'description' => 'I built a streamlined direct-to-consumer delivery and sales application. I integrated a frictionless consumer checkout system with a detailed sales analysis dashboard tracking customer retention rates, cohort payment patterns, and regional order distributions.',
                'significant_figure' => 'D2C Checkout Pipeline',
                'problem' => 'Friction in managing live inventory sync against sudden orders, combined with a lack of retention data.',
                'methodology' => 'We formulated optimized inventory transactional locks and custom retention analysis queries to track returning buyers.',
                'outcome' => 'Created a seamless juice distribution app, optimizing delivery routing and stock replenishment schedules.',
                'image' => '/assets/images/custom-webdev.png',
                'is_featured' => true,
            ],
            [
                'type' => 'client',
                'title' => 'Reytati Communications Agency Digital Workspace',
                'client_name' => 'Reytati Communications',
                'category' => 'Marketing & Brand Communications',
                'technologies' => ['React', 'LAMP Stack', 'Lead Capture Engines'],
                'description' => 'I engineered a dynamic, single-page interactive agency application. I integrated custom business profile documentation with an asynchronous client intake and lead capture engine, backed by an admin panel for dynamic testimonial administration and service catalog updates.',
                'significant_figure' => 'Asynchronous Intake',
                'problem' => 'Low user conversion rates from static intake files and slow content changes.',
                'methodology' => 'We designed polished SPA transitions and mapped dynamic intake flows to streamline onboarding and feedback.',
                'outcome' => 'Significantly increased lead captures via responsive forms, backing it with an easy catalog manager.',
                'image' => '/assets/images/uiux-design.png',
                'is_featured' => true,
            ],
            [
                'type' => 'client',
                'title' => 'Pan-African Digital Policy & Tech Governance Suite',
                'client_name' => 'Lawyers Hub & United Nations ECA',
                'category' => 'GovTech / Tech-Policy',
                'technologies' => ['Tech-Policy Analysis', 'Multilingual DB', 'Event APIs'],
                'description' => 'I deployed a suite of digital governance platforms. I spearheaded the development of the Lawyers Hub Digital Policy Knowledgebase and designed the UX/UI for the AI Policy Lab virtual environment, the Africa Law Tech University, and the Africa Law Tech Festival. I also co-developed the bilingual (French/English) African AI Startup Database in collaboration with the UN ECA.',
                'significant_figure' => 'Multilingual Policy DB',
                'problem' => 'Scattered policy files and language barriers restricting unified digital startup coordination across different jurisdictions.',
                'methodology' => 'We designed pan-African digital policy libraries and multilingual database schemas mapping tech startup attributes.',
                'outcome' => 'Facilitated digital policy education, regional governance forums, and startup tracking at a continent-wide scale.',
                'image' => '/assets/images/digital-strategy.png',
                'is_featured' => true,
            ],
            [
                'type' => 'client',
                'title' => 'Najenga Collaborative Construction Web App',
                'client_name' => 'Najenga',
                'category' => 'PropTech / Collaborative Software',
                'technologies' => ['HTML5 Canvas API', 'Interactive Timelines', 'Document Systems'],
                'description' => 'I architected a specialized construction project coordination web application designed to bridge the communication gap between field engineers, architects, project managers, and clients. I centralized the review of architectural drawings, designed interactive timelines, and engineered a media workspace with coordinate-based canvas annotation support for remote site inspection.',
                'significant_figure' => 'HTML5 Canvas Markup',
                'problem' => 'Siloed communication during blueprint modifications, causing delays in structural changes between site and office.',
                'methodology' => 'We built a spatial canvas engine for real-time document annotation, combined with interactive coordinate timelines.',
                'outcome' => 'Allowed engineering teams to draw directly on digital plans from site tablets, accelerating blueprint review phases.',
                'image' => '/assets/images/custom-webdev.png',
                'is_featured' => true,
            ],
            [
                'type' => 'client',
                'title' => 'The Football Experience Fintech Travel Platform',
                'client_name' => 'The Football Experience',
                'category' => 'FinTech / Travel Logistics',
                'technologies' => ['React', 'FinTech Ledgers', 'Micro-Financing Algorithms', 'Encryption'],
                'description' => 'I engineered a FinTech and logistics platform designed to democratize access to global sporting events for African users. I implemented custom virtual wallet ledgers, installment financing schedulers, user dashboards, and real-time social discovery feeds.',
                'significant_figure' => 'Virtual Financing Schedulers',
                'problem' => 'Complex travel financing calculations, repayment tracking, and high transactional security demands.',
                'methodology' => 'We managed micro-ledgers via secure state machines and designed mathematical algorithms to schedule installment repayments.',
                'outcome' => 'Empowered users to plan and pay for events through automated, secure installment models.',
                'image' => '/assets/images/digital-strategy.png',
                'is_featured' => true,
            ],
            [
                'type' => 'client',
                'title' => 'Nyalife Secure Clinical Administration System',
                'client_name' => 'Nyalife Women\'s Health Clinic',
                'category' => 'HealthTech / Clinic Operations',
                'technologies' => ['PHP', 'React', 'Healthcare DB Schema', 'ACL Security'],
                'description' => 'I built a secure patient-doctor management and clinical administration portal. I standardized patient records processing, appointment scheduling, and clinical file handling to optimize operations while preserving data privacy. I deployed this system under strict security parameters.',
                'significant_figure' => '65% Efficiency Increase',
                'problem' => 'Disconnected patient charts, scheduling overlap risks, and strict health data privacy standards.',
                'methodology' => 'We designed secure patient schemas, implemented Access Control Lists (ACL), and built real-time booking charts.',
                'outcome' => 'Created a secure portal protecting sensitive health charts, reducing waiting times and paperwork loads.',
                'image' => '/assets/images/uiux-design.png',
                'is_featured' => true,
            ],
            [
                'type' => 'client',
                'title' => 'DnT Event Coordination Platform',
                'client_name' => 'Private Client',
                'category' => 'EventTech / Hospitality',
                'technologies' => ['LAMP Stack', 'Image Optimization', 'SMTP Queues', 'Dynamic States'],
                'description' => 'I designed and deployed a dynamic live event tracking and guest coordination system. I integrated automated RSVPs, email correspondence queues, dynamic CMS portfolio adjustments, and real-time photo gallery upload management to capture event activities live.',
                'significant_figure' => 'Real-time Live Moments',
                'problem' => 'Handling high-volume concurrent guest image uploads during live events and queuing automated RSVP updates.',
                'methodology' => 'We engineered image optimization pipelines and managed multi-step guest reservation confirmation queues.',
                'outcome' => 'Enabled immediate live gallery updates during events with automated tracking for thousands of RSVP statuses.',
                'image' => '/assets/images/uiux-design.png',
                'is_featured' => true,
            ],
        ];

        foreach ($projects as $project) {
            Project::updateOrCreate(
                ['slug' => Str::slug($project['title'])],
                $project
            );
        }

        // Flagship Projects
        $flagshipProjects = [
            [
                'type' => 'flagship',
                'title' => 'Tibu: Market Intelligence & Policy Sandbox',
                'tagline' => 'Bridging the gap between tech and policy.',
                'category' => 'LegalTech & Policy',
                'technologies' => ['Next.js', 'PostgreSQL', 'DeepSeek AI', 'Tailwind'],
                'description' => '<p>Tibu is OKJTech\'s proprietary market intelligence platform designed for the African digital ecosystem. It facilitates real-time policy analysis and stakeholder engagement.</p>',
                'significant_figure' => '100% Policy Visibility',
                'problem' => '<p>Digital entrepreneurs and policymakers often work in silos, leading to regulatory friction. There was no centralized repository for real-time digital policy tracking across varied jurisdictions.</p>',
                'methodology' => '<p>We architected Tibu using a vector-database approach to index regulatory documents. We implemented a clean, dashboard-first UI/UX to make complex legal data digestible for non-technical stakeholders.</p>',
                'outcome' => '<p>Tibu has become a go-to resource for Lawyers Hub and other regional stakeholders, reducing policy feedback cycles from months to days through automated reporting and alert systems.</p>',
                'image' => 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80',
                'url' => 'https://okjtech.io/tibu',
                'is_featured' => true,
            ],
            [
                'type' => 'flagship',
                'title' => 'Naoa: Living Wedding Memories',
                'tagline' => 'Documenting love as it happens.',
                'category' => 'Events & Lifestyle',
                'technologies' => ['React', 'Laravel', 'AWS S3', 'Pusher'],
                'description' => '<p>A comprehensive digital ecosystem for modern weddings, featuring live gallery updates, guest onboarding, and immersive digital scrapbooks.</p>',
                'significant_figure' => '5k+ Active Moments',
                'problem' => '<p>Wedding memories are often fragmented across multiple devices and social media platforms. Couples lack a central, high-quality "living" record of their celebration as it unfolds.</p>',
                'methodology' => '<p>We built Naoa with a mobile-first philosophy, focusing on high-concurrency photo uploads and real-time push notifications. The architecture ensures that every guest interaction is recorded and displayed instantly.</p>',
                'outcome' => '<p>Naoa has transformed dozens of events into searchable, interactive digital experiences, with an average guest engagement rate of over 85% during the event window.</p>',
                'image' => 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80',
                'url' => 'https://dntwed.okjtech.co.ke',
                'is_featured' => true,
            ],
        ];

        foreach ($flagshipProjects as $project) {
            Project::updateOrCreate(
                ['slug' => Str::slug($project['title'])],
                $project
            );
        }
    }
}
